### ISSUE TITLE
No space on device 

### ISSUE THREAD

**Issue by hohu05** [LinusCDE/rmTouchToggler#2]
In the updated version of the Remarkable it is not possible to copy the file to /etc/systemd/system/ because there is no free space in the root partition. A symbolic link does not work.

**Comment by LinusCDE** [comment]
The device currently keeps filling the little space that's left (about 20mb) with systemd logs until there is no more space.

Either run this command `journalctl --vacuum-time=2d` to free up space maybe increase the days if it does  ot work).

Or limit the size in */etc/systemd/journald.conf* (System logs max something).

You can see the space on the device with `df -h`.
